# Site settings
title: Daniel Flores Aguilar
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Flores
user_description: Mobile devices developer and Web Developer
user_title: Mobile Engineer
email: daniel.flores.fullstack@gmail.com
twitter_username: dummy_twitter
github_username:  danieleven
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Android
    url: /android
  - title: iOS
    url: /tags
  - title: Python ¬ Django
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
